#!/usr/bin/env python3
"""Gate: every rule in primitives.css must match what tailwind currently generates for that class.

primitives.css takes over those class names when the tailwind entry is dropped, so any drift between
our hand-held copy and tailwind's output would change rendering at the handover. This compares the two
while both exist, which is the only window in which the comparison is possible.

Skipped automatically once dist/glue/app.css no longer contains a tailwind utilities layer (ie after
the handover), because at that point primitives.css IS the definition.

Run from client/. Wired into build.sh.
"""
import re
import sys
import pathlib

PRIM = pathlib.Path("glue/css/primitives.css")
BUILT = pathlib.Path("dist/glue/app.css")


def decls(block):
    out = {}
    for d in block.split(";"):
        if ":" in d:
            k, v = d.split(":", 1)
            out[k.strip().lower()] = re.sub(r"\s+", " ", v.strip())
    return out


def main():
    if not PRIM.exists():
        print("check-primitives-parity: no primitives.css yet, nothing to check")
        return 0
    if not BUILT.exists():
        print("check-primitives-parity: no built css yet, skipping")
        return 0
    built = BUILT.read_text(encoding="utf-8")
    if "@layer utilities" not in built:
        print("check-primitives-parity: tailwind utilities gone, primitives.css is now the definition")
        return 0

    bad, checked = [], 0
    for m in re.finditer(r"^\.([\w-]+)\s*\{([^{}]*)\}", PRIM.read_text(encoding="utf-8"), flags=re.M):
        cls, ours = m.group(1), decls(m.group(2))
        hit = re.search(r"(?<![\w.\\-])\." + re.escape(cls) + r"\s*\{([^{}]*)\}", built)
        if not hit:
            bad.append((cls, "not generated by tailwind", ours, {}))
            continue
        theirs = decls(hit.group(1))
        checked += 1
        if ours != theirs:
            bad.append((cls, "declarations differ", ours, theirs))

    print(f"primitives checked against tailwind output: {checked}, mismatched: {len(bad)}")
    if bad:
        for cls, why, ours, theirs in bad:
            print(f"  MISMATCH .{cls}: {why}\n    ours:   {ours}\n    theirs: {theirs}")
        print("\nprimitives parity: FAIL")
        return 1
    print("primitives parity: PASS (every primitive matches tailwind's own output)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
